[package]
name = "leptos-form-proc-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
core = { package = "leptos-form-proc-macros-core", path = "./core" }
