[package]
name = "leptos_form"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
leptos.workspace = true
leptos_form_core.path = "../core"
leptos_form_proc_macros.path = "../proc_macros"
leptos_router.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true

bigdecimal = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
num-bigint = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[features]
bigdecimal = ["dep:bigdecimal", "leptos_form_core/bigdecimal"]
chrono = ["dep:chrono", "leptos_form_core/chrono"]
num-bigint = ["dep:num-bigint", "leptos_form_core/num-bigint"]
uuid = ["dep:uuid", "leptos_form_core/uuid"]
