[package]
name = "leptos_form_proc_macros_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
convert_case.workspace = true
darling.workspace = true
derive_more.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
prettyplease.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
