[package]
name = "leptos-form-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version = "1.75.0"

[dependencies]
cfg-if.workspace = true
leptos.workspace = true
num-traits.workspace = true
paste.workspace = true
thiserror.workspace = true
typed-builder.workspace = true
web-sys.workspace = true

chrono = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[features]
chrono = ["dep:chrono"]
uuid = ["dep:uuid"]
