[package]
name = "leptos_form_proc_macros"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
leptos_form_proc_macros_core.path = "./core"

[lib]
proc-macro = true
