name: CD

on:
  push:
    branches:
    - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly-2023-11-01

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v4-rust"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_PLZ_TOKEN }}

    - name: Run release-plz
      uses: MarcoIeni/release-plz-action@v0.5
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
