name: CI

on:
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # TODO: change to dtolnay/rust-toolchain@stable once 1.75.0 lands on stable
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2023-11-01
        components: clippy,rustfmt

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1-rust"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - run: cargo install cargo-machete --locked

    - run: cargo install cargo-deny --locked

    - run: touch requirements.txt
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip" # caching pip dependencies
    - run: rm requirements.txt

    - run: pip install pre-commit

    - uses: actions/checkout@v4

    - run: pre-commit run --all-files --hook-stage push

    - name: rust-grcov
      uses: actions-rs/grcov@v0.1

    - name: Codecov
      uses: codecov/codecov-action@v4-beta
      continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        # token: # optional
        # Specify whether the Codecov output should be verbose
        verbose: true
        fail_ci_if_error: false
